### PR TITLE
Logout

### PR DESCRIPTION
**Pull request by vfurmane**
Waiting to merge https://github.com/vfurmane/ft_transcendence/pull/54 first

### CODE REVIEW

**Review by deblokc — APPROVED** [review]

**Comment by soleraeus** [comment]
> Waiting to merge #54 first

I merged #54 
Will have to mix and match with what I did in the front in #57 (should take a minute or so)

**Comment by vfurmane** [comment]
Need to close websockets on logout (cf. #57)

**Comment by vfurmane** [comment]
Websockets were already closed by the Websocket component's `useEffect`.

**Review by deblokc — APPROVED** [review]

**Review by soleraeus — APPROVED** [review]
Looks good

**Review by maxenceeudier — APPROVED** [review]

**Review by savosaicic — APPROVED** [review]

**Pull request merged**
